debug: false
uuid: b72db02b-33fe-4172-b159-0c756179dd94
token_id: Ig7j9IpB3ay5ZTqp
token: iDlhygaf04pDotZj9lSgQZFdq9Fv826tuN5dosUEgTulhiY9kFitxPTZa67QgC3m
api:
  host: 0.0.0.0
  port: 448
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/meet-wallaby-caring.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/meet-wallaby-caring.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://vigilant-train-q797pg574v6gh49j9-80.app.github.dev'
