debug: false
uuid: 823e7775-e415-4ec0-9672-ec3a0bf48ea6
token_id: FhAD2U5fvscPnOQl
token: wJ6aQ4bgEGWj2k8LBlYqp4qirnAW3BlWdZdTsb6EzNVyUmaDqWJQ6drK66qRpYGP
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/meet-wallaby-caring.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/meet-wallaby-caring.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://supreme-meme-r4r4pv5464rgfx5vx-80.app.github.dev'
